// examples/react/src/components/FrillWidget.tsx
import React from 'react';

const FrillWidget: React.FC = React.memo(() => {
  // This effect will run once when the component has mounted
  React.useEffect(() => {
    const widget = window.Frill('widget', {
      key: 'YOUR_WIDGET_KEY', // <-- Add Widget key here
    });

    return () => {
      widget.destroy();
    };
  }, []);

  // We are going to render a button that will be used to open the widget. This is because
  // the example widget is using a "CSS selector" for the "Launcher".
  // If your widget does not use this launcher, you can return null.
  return (
    <button type='button' className='frill-container btn'>
      Click here to show the Widget
    </button>
  );
});

export default FrillWidget;

// examples/vue/src/components/FrillWidget.vue
<template>
  <button type="button" class="frill-container btn">
    Click here to show the Widget
  </button>
</template>

<script lang="ts">
/* eslint-disable @typescript-eslint/camelcase,@typescript-eslint/no-explicit-any */
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'FrillWidget',
  data: () => ({
    widget: undefined as FrillWidget | undefined,
    config: undefined as FrillConfig | undefined,
  }),
  mounted() {
    this.setupFrillWidget();
  },
  beforeUnmount() {
    if (this.widget) {
      this.widget.destroy();
      this.widget = undefined;
    }

    if (this.config) {
      window.Frill_Config = window.Frill_Config.filter((c) => c !== this.config);
    }
  },
  methods: {
    setupFrillWidget() {
      this.config = {
        key: 'YOUR_WIDGET_KEY', // <-- Add Widget key here
        callbacks: {
          onReady: (frillWidget) => {
            this.widget = frillWidget;
          },
        },
      };

      window.Frill_Config = window.Frill_Config || [];
      window.Frill_Config.push(this.config);

      if ('Frill' in window) {
        this.widget = window.Frill.widget(this.config);
      }
    },
  },
});
</script>
